apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anaconda-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi


