version: '3'

networks:
  proxy:
      external: true

services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik
    restart: always
    command: --web --docker
    networks:
      - proxy       
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik.toml:/traefik.toml
      - acme.json:/acme.json
    labels:
      - traefik.frontend.rule=Host:monitor.fluxcapacitor.cloud
      - traefik.port=8080
