debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
	[entryPoints.http.redirect]
	entryPoint = "https"
	[entryPoints.https]
	address = ":443"
	[entryPoints.https.tls]

	[retry]
	
[entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth.basic]
    users = ["admin:$apr1$o1PiIw2r$F8Pp.PFVIL/LpWf4mJsdy0"]

[api]
entryPoint = "traefik"


[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false

[acme]
email = "matteo.creati@gmail.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
	entryPoint = "http"

[[acme.domains]]
  main = "guacamole.octotrading.it"
[[acme.domains]]
  main = "monitor.octotrading.it"

