apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guacd
spec:
  selector:
    matchLabels:
      run: guacd
  replicas: 1
  template:
    metadata:
      labels:
        run: guacd
    spec:
      containers:
      - name: guacd
        image: guacamole/guacd

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guacamole
spec:
  selector:
    matchLabels:
      run: guacamole
  replicas: 1
  template:
    metadata:
      labels:
        run: guacamole
    spec:
      containers:
      - name: guacamole
        image: guacamole/guacamole
        env:
        - name: GUACAMOLE_HOME
          value: /opt/guacamole/home
        - name: GUACD_HOSTNAME
          value: "guacd"
        - name: GUACD_PORT
          value: "4822"
#        - name: MYSQL_HOSTNAME
#          value: "guacamole-mysql"
#        - name: MYSQL_PORT
#          value: "3306"
#        - name: MYSQL_DATABASE
#          value: "guacamole_db"
#        - name: MYSQL_USER
#          value: "guacamole"
#        - name: MYSQL_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: mysql-pass
#              key: password
        volumeMounts:
          - name: guacamole-persistent-storage
            mountPath: /opt/guacamole/home
      volumes:
      - name: guacamole-persistent-storage
        persistentVolumeClaim:
          claimName: guacamole-managed-disk
