version: '3'

services:
   guacd:
    container_name: guacd       
    image: guacamole/guacd
    restart: unless-stopped
    networks:
      - guac 
   guacamole: 
    container_name: guacamole
    image: guacamole/guacamole
    restart: unless-stopped
    networks:
      - guac
      - proxy
    ports:
      - 8080
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guac-mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      LDAP_HOSTNAME: ${LDAP_HOSTNAME}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_USER_BASE_DN: ${LDAP_USER_BASE_DN}
      LDAP_CONFIG_BASE_DN: ${LDAP_CONFIG_BASE_DN}
      LDAP_SEARCH_BIND_DN: ${LDAP_SEARCH_BIND_DN}
      LDAP_USERNAME_ATTRIBUTE: ${LDAP_USERNAME_ATTRIBUTE}
      LDAP_SEARCH_BIND_PASSWORD: ${LDAP_SEARCH_BIND_PASSWORD}
    labels:
      - "traefik.backend=guacamole"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=Host:publicdnsname"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.default.protocol=http"

networks:
   guac:
     driver: bridge
   proxy:
      external: true
